import fs from "fs";
import path from "path";
import type { TaxonomyNode } from "./buildTaxonomyTree";

const TREE_FILE = path.join(process.cwd(), "data", "taxonomy-tree.json");

/**
 * Read the pre-built taxonomy tree from data/taxonomy-tree.json.
 * This file is generated by `node build_taxonomy_tree.js`.
 */
export function getTaxonomyTree(): TaxonomyNode {
  const raw = fs.readFileSync(TREE_FILE, "utf-8");
  return JSON.parse(raw) as TaxonomyNode;
}
