"use client";

import { useState, useEffect } from "react";
import { MessageSquare, Save, Loader2, ChevronDown } from "lucide-react";
import { useLanguage } from "@/lib/LanguageContext";

export default function MessageBoard() {
  const { lang } = useLanguage();
  const [comment, setComment] = useState("");
  const [saved, setSaved] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem("wild_explorer_comment_draft");
    if (stored) setComment(stored);
  }, []);

  const handleChange = (val: string) => {
    setComment(val);
    localStorage.setItem("wild_explorer_comment_draft", val);
  };

  const handleSave = async () => {
    if (!comment.trim()) return;
    setLoading(true);
    
    try {
      await fetch('/api/comments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ comment })
      });
      setSaved(true);
      setComment("");
      localStorage.removeItem("wild_explorer_comment_draft");
      setTimeout(() => setSaved(false), 3000);
    } catch (e) {
      console.error("Failed to save comment", e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white/90 backdrop-blur-sm rounded-2xl lg:rounded-3xl p-3 lg:p-5 shadow-sm border border-slate-100 flex flex-col h-full">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between w-full text-left lg:cursor-default lg:pointer-events-none group"
      >
        <div className="flex items-center gap-2 text-amber-500">
          <MessageSquare size={18} strokeWidth={2.5} />
          <h3 className="font-bold text-slate-800 text-sm tracking-tight transition-colors group-hover:text-amber-600 lg:group-hover:text-slate-800">
            {lang === "en" ? "Feedback & Comments" : "留言与反馈"}
          </h3>
        </div>
        <ChevronDown 
          size={18} 
          className={`lg:hidden transition-transform duration-300 text-slate-400 ${isOpen ? "rotate-180" : ""}`} 
        />
      </button>
      
      <div className={`grid transition-all duration-300 ease-in-out lg:!grid-rows-[1fr] lg:!opacity-100 lg:!mt-3 ${
        isOpen ? 'grid-rows-[1fr] opacity-100 mt-3' : 'grid-rows-[0fr] opacity-0 mt-0 pt-0'
      }`}>
        <div className="overflow-hidden min-h-0 flex flex-col gap-3">
          <p className="text-xs text-slate-500 font-medium leading-relaxed">
            {lang === "en" 
              ? "All contents generated by AI. Notice a mistake or have comments? write it down below:" 
              : "所有内容均由AI生成。发现错误或有任何建议？请在下方留言："}
          </p>

          <textarea
            value={comment}
            onChange={(e) => handleChange(e.target.value)}
            placeholder={lang === "en" ? "Type your thoughts here..." : "在此输入你的想法..."}
            className="w-full h-24 p-3 text-sm bg-slate-50 text-slate-700 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-amber-200 focus:border-amber-400 transition-all resize-none"
          />

          <button
            onClick={handleSave}
            disabled={loading || !comment.trim()}
            className={`mt-1 flex items-center justify-center gap-2 py-2 rounded-xl text-xs font-bold transition-all duration-200 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed ${
              saved 
                ? "bg-emerald-500 text-white shadow-emerald-200/50" 
                : "bg-slate-800 text-white hover:bg-slate-700 hover:shadow-md active:scale-95"
            }`}
          >
            {loading ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} strokeWidth={2.5} />}
            <span>{saved ? (lang === "en" ? "Saved!" : "已保存") : (lang === "en" ? "SAVE" : "保存")}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
